// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timelines.Data;

#nullable disable

namespace Timelines.Data.Migrations
{
    [DbContext(typeof(TimelinesDbContext))]
    [Migration("20260225162005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timelines.Data.Entities.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailBlobKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.ItemTagEntity", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.LaneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TimelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TimelineId");

                    b.HasIndex("TimelineId", "Name")
                        .IsUnique();

                    b.ToTable("Lanes", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.ShareLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TimelineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.HasIndex("TimelineId");

                    b.ToTable("ShareLinks", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TimelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TimelineId");

                    b.HasIndex("TimelineId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.TimelineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DefaultView")
                        .HasColumnType("int");

                    b.Property<int>("DefaultZoom")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Timelines", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.TimelineItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrderTiebreaker")
                        .HasColumnType("int");

                    b.Property<long?>("EndSortKey")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("LaneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("StartSortKey")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TimelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LaneId");

                    b.HasIndex("StartSortKey");

                    b.HasIndex("TimelineId");

                    b.ToTable("TimelineItems", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Timelines.Data.Entities.AttachmentEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.TimelineItemEntity", "Item")
                        .WithMany("Attachments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Timelines.Data.Entities.ItemTagEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.TimelineItemEntity", "Item")
                        .WithMany("ItemTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timelines.Data.Entities.TagEntity", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Timelines.Data.Entities.LaneEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.TimelineEntity", "Timeline")
                        .WithMany("Lanes")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Timelines.Data.Entities.ShareLinkEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.TimelineEntity", "Timeline")
                        .WithMany("ShareLinks")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Timelines.Data.Entities.TagEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.TimelineEntity", "Timeline")
                        .WithMany("Tags")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Timelines.Data.Entities.TimelineItemEntity", b =>
                {
                    b.HasOne("Timelines.Data.Entities.LaneEntity", "Lane")
                        .WithMany("Items")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timelines.Data.Entities.TimelineEntity", "Timeline")
                        .WithMany("Items")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Timelines.Data.Entities.DateComponent", "EndDate", b1 =>
                        {
                            b1.Property<Guid>("TimelineItemEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Day")
                                .HasColumnType("int")
                                .HasColumnName("EndDay");

                            b1.Property<int>("Era")
                                .HasColumnType("int")
                                .HasColumnName("EndEra");

                            b1.Property<bool>("IsApprox")
                                .HasColumnType("bit")
                                .HasColumnName("EndIsApprox");

                            b1.Property<int?>("Month")
                                .HasColumnType("int")
                                .HasColumnName("EndMonth");

                            b1.Property<int>("Precision")
                                .HasColumnType("int")
                                .HasColumnName("EndPrecision");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("EndYear");

                            b1.HasKey("TimelineItemEntityId");

                            b1.ToTable("TimelineItems");

                            b1.WithOwner()
                                .HasForeignKey("TimelineItemEntityId");
                        });

                    b.OwnsOne("Timelines.Data.Entities.DateComponent", "StartDate", b1 =>
                        {
                            b1.Property<Guid>("TimelineItemEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Day")
                                .HasColumnType("int")
                                .HasColumnName("StartDay");

                            b1.Property<int>("Era")
                                .HasColumnType("int")
                                .HasColumnName("StartEra");

                            b1.Property<bool>("IsApprox")
                                .HasColumnType("bit")
                                .HasColumnName("StartIsApprox");

                            b1.Property<int?>("Month")
                                .HasColumnType("int")
                                .HasColumnName("StartMonth");

                            b1.Property<int>("Precision")
                                .HasColumnType("int")
                                .HasColumnName("StartPrecision");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("StartYear");

                            b1.HasKey("TimelineItemEntityId");

                            b1.ToTable("TimelineItems");

                            b1.WithOwner()
                                .HasForeignKey("TimelineItemEntityId");
                        });

                    b.Navigation("EndDate");

                    b.Navigation("Lane");

                    b.Navigation("StartDate")
                        .IsRequired();

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Timelines.Data.Entities.LaneEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Timelines.Data.Entities.TagEntity", b =>
                {
                    b.Navigation("ItemTags");
                });

            modelBuilder.Entity("Timelines.Data.Entities.TimelineEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Lanes");

                    b.Navigation("ShareLinks");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Timelines.Data.Entities.TimelineItemEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
